version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - ./local_dev/static_files:/app/static-dump
      - ./local_dev/medias:/app/medias
      - ./local_dev/database:/app/database
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DJANGO_SUPERUSER_PASSWORD=password
    ports:
      - 8000:8000
